cd ../..
cd dataset
mkdir dmsp-ols
cd dmsp-ols
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F101992.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F101993.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F101994.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121994.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121995.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121996.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121997.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121998.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F121999.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F141997.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F141998.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F141999.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F142000.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F142001.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F142002.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F142003.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152000.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152001.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152002.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152003.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152004.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152005.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152006.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F152007.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162004.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162005.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162006.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162007.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162008.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F162009.v4b.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F182010.v4c.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F182011.v4c.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F182012.v4c.avg_lights_x_pct.tgz
wget https://ngdc.noaa.gov/eog/data/web_data/v4avg_lights_x_pct/F182013.v4c.avg_lights_x_pct.tgz